/* eslint-disable */
require('./arrow-left')
require('./arrow-up')
require('./box')
require('./double-arrow-left')
require('./lock')
require('./person')
require('./phone')
require('./search')
require('./Vector')
